output_dir: ~/scratch/torchprotein_output/

dataset:
  class: BindingDB
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"
        keys: "graph1"

test_split: holdout_test

task:
  class: InteractionPrediction
  model:
    class: ProteinResNet
    input_dim: 21
    hidden_dims: [ 512, 512, 512, 512, 512, 512, 512, 512 ]
    layer_norm: True
    dropout: 0.1
  model2:
    class: GIN
    input_dim: 66
    hidden_dims: [ 256, 256, 256, 256 ]
    batch_norm: yes
    short_cut: yes
    concat_hidden: yes
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]
  num_mlp_layer: 2
  normalization: False

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 32

train:
  num_epoch: 100