output_dir: ~/scratch/torchprotein_output/

dataset:
  class: Fold
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

test_split: test_fold_holdout

task:
  class: PropertyPrediction
  model:
    class: ProteinResNet
    input_dim: 21
    hidden_dims: [ 512, 512, 512, 512, 512, 512, 512, 512 ]
    layer_norm: True
    dropout: 0.1
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 1195

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 16

train:
  num_epoch: 100