output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: cb513
    center: True
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 500
          random: True
        - class: ProteinView
          view: "residue"
  - class: ProteinNet
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 1022
          random: False
        - class: ProteinView
          view: "residue"

tasks:
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: 3
  - class: ContactPrediction
    criterion: bce
    metric: [ "accuracy", "prec@L5", "prec@5" ]
    max_length: 300
    random_truncate: yes
    threshold: 8.0
    gap: 6
    num_mlp_layer: 2

model:
  class: ProteinBERT
  input_dim: 21
  hidden_dim: 512
  num_layers: 4
  num_heads: 8
  intermediate_dim: 2048
  hidden_dropout: 0.1
  attention_dropout: 0.1

eval_metric: Center - SecondaryStructure macro_acc

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 16

train:
  num_epoch: 100
  tradeoff: 1.0