output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: PDBBind
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    center: True
    test_split: test
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"
          keys: "graph1"
  - class: ProteinNet
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 1022
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: InteractionPrediction
    model2:
      class: GIN
      input_dim: 66
      hidden_dims: [256, 256, 256, 256]
      batch_norm: yes
      short_cut: yes
      concat_hidden: yes
    normalization: False
    criterion: mse
    metric: ["mae", "rmse", "spearmanr"]
    num_mlp_layer: 2
  - class: ContactPrediction
    criterion: bce
    metric: [ "accuracy", "prec@L5", "prec@5" ]
    max_length: 300
    random_truncate: yes
    threshold: 8.0
    gap: 6
    num_mlp_layer: 2

model:
  class: ProteinConvolutionalNetwork
  input_dim: 21
  hidden_dims: [1024, 1024]
  kernel_size: 5
  padding: 2

eval_metric: Center - PDBBind root mean squared error

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
  tradeoff: 1