output_dir: ~/scratch/torchprotein_output/

dataset:
  class: PPIAffinity
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: Physicochemical
    path: ~/scratch/physicochemical
    type: moran
    nlag: 30
    hidden_dims: [512]
  normalization: False
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  num_mlp_layer: 2

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 16

train:
  num_epoch: 100