output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: BinaryLocalization
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    center: True
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 550
          random: False
        - class: ProteinView
          view: "residue"
  - class: ProteinNet
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 1022
          random: False
        - class: ProteinView
          view: "residue"

tasks:
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: 2
  - class: ContactPrediction
    criterion: bce
    metric: [ "accuracy", "prec@L5", "prec@5" ]
    max_length: 100
    random_truncate: yes
    threshold: 8.0
    gap: 6
    num_mlp_layer: 2

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b
  readout: mean

eval_metric: Center - BinaryLocalization accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2

train:
  num_epoch: 100
  tradeoff: 0.5