output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: HumanPPI
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: test
    center: True
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 550
          random: False
          keys: [ "graph1", "graph2" ]
        - class: ProteinView
          view: "residue"
          keys: [ "graph1", "graph2" ]
  - class: Fold
    path: ~/scratch/protein-datasets/
    test_split: test_fold_holdout
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: InteractionPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: 2
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: 1195

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b
  readout: mean

eval_metric: Center - HumanPPI accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

lr_ratio: 0.01

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 1

train:
  num_epoch: 50
  tradeoff: 1.0