output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: PDBBind
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    center: True
    test_split: test
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 550
          random: True
          keys: "graph1"
        - class: ProteinView
          view: "residue"
          keys: "graph1"
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: cb513
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: InteractionPrediction
    model2:
      class: GIN
      input_dim: 66
      hidden_dims: [256, 256, 256, 256]
      batch_norm: yes
      short_cut: yes
      concat_hidden: yes
    normalization: False
    criterion: mse
    metric: ["mae", "rmse", "spearmanr"]
    num_mlp_layer: 2
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: 3

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b

eval_metric: Center - PDBBind root mean squared error

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2

lr_ratio: 0.1

train:
  num_epoch: 100
  tradeoff: 1