output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: Stability
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    center: True
    transform:
      class: Compose
      transforms:
        - class: ProteinView
          view: "residue"
  - class: Fold
    path: ~/scratch/protein-datasets/
    test_split: test_fold_holdout
    atom_feature: null
    bond_feature: null
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: PropertyPrediction
    criterion: mse
    metric: [ "mae", "rmse", "spearmanr" ]
    normalization: False
    num_mlp_layer: 2
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: 1195

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b
  readout: mean

eval_metric: Center - Stability spearmanr

optimizer:
  class: Adam
  lr: 1.0e-5

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
  tradeoff: 1.0