output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: YeastPPI
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: test
    center: True
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 550
          random: True
          keys: [ "graph1", "graph2" ]
        - class: ProteinView
          view: "residue"
          keys: [ "graph1", "graph2" ]
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    atom_feature: null
    bond_feature: null
    test_split: cb513
    transform:
      class: Compose
      transforms:
        - class: TruncateProtein
          max_length: 200
          random: True
        - class: ProteinView
          view: "residue"

tasks:
  - class: InteractionPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: 2
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: 3

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b
  readout: mean

eval_metric: Center - YeastPPI accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 1

train:
  num_epoch: 100
  tradeoff: 1.0