output_dir: ~/scratch/torchprotein_output/

dataset:
  class: ProteinNet
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

test_split: test
test_batch_size: 1

task:
  class: ContactPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
  criterion: bce
  metric: ["accuracy", "prec@L5", "prec@5"]
  max_length: 400
  random_truncate: yes
  threshold: 8.0
  gap: 6
  num_mlp_layer: 2

eval_metric: prec@L5

optimizer:
  class: Adam
  lr: 5.0e-5

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2

train:
  num_epoch: 50