output_dir: ~/scratch/torchprotein_output/

dataset:
  class: PPIAffinity
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: False
        keys: [ "graph1", "graph2" ]
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
    readout: mean
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]
  num_mlp_layer: 2
  normalization: False

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True
fix_encoder2: True

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
