output_dir: ~/scratch/torchprotein_output/

dataset:
  class: SubcellularLocalization
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 10

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2

train:
  num_epoch: 100