output_dir: /scratch/ulab222/PEER-xxx-seed0/torchprotein_output/

dataset:
  class: Fold
  path: /scratch/ulab222/PEER-xxx-seed0/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
      - class: ProteinView
        view: "residue"

test_split: test_fold_holdout

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: /scratch/ulab222/PEER-xxx-seed0/esm-model-weights/
    model: ESM2-650
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  #gpus: [0, 1, 2, 3]
  batch_size: 4

lr_ratio: 0.1

train:
  num_epoch: 100