output_dir: /scratch/ulab222/PEER-xxx-seed0/torchprotein_output/

dataset:
  class: HumanPPI
  path: /scratch/ulab222/PEER-xxx-seed0/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ESM
    path: /scratch/ulab222/PEER-xxx-seed0/esm-model-weights/
    model: ESM2-650
    readout: mean
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True
fix_encoder2: True

engine:
  #gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 50