output_dir: /scratch/ulab222/PEER-xxx-seed0/torchprotein_output/

dataset:
  class: PPIAffinity
  path: /scratch/ulab222/PEER-xxx-seed0/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
        keys: [ "graph1", "graph2" ]
      - class: ProteinView
        view: "residue"
        keys: [ "graph1", "graph2" ]

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ESM
    path: /scratch/ulab222/PEER-xxx-seed0/esm-model-weights/
    model: ESM2-650
  normalization: False
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  num_mlp_layer: 2

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  #gpus: [0, 1, 2, 3]
  batch_size: 2

lr_ratio: 0.1

train:
  num_epoch: 100